service: booking-organizer-lambda-user
provider:
  name: aws
  runtime: nodejs16.x
  environment:
    APP_VERSION: ${file(./package.json):version}
  httpApi:
    cors: true
functions:
  graphql:
    # Make sure your file path is correct!
    # (e.g., if your file is in the root folder use server.graphqlHandler )
    # The format is: <FILENAME>.<HANDLER>
    handler: lambda.handleHttpUsers # highlight-line
    events:
      - httpApi:
          path: /
          method: POST
      - httpApi:
          path: /
          method: GET
# Omit the following lines if you aren't using TS!
plugins:
  - serverless-esbuild
  - serverless-offline
custom:
  esbuild:
    bundle: true
    minify: false
  serverless-offline:
    httpPort: 6000
    websocketPort: 6001
    lambdaPort: 6002
