service: test-lambda-authorizer
provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  runtime: nodejs16.x
  environment:
    APP_VERSION: ${file(./package.json):version}
    APP_ENV: ${self:provider.stage}
    APP_TEST: ${file(./config/${self:provider.stage}.json):aws.test}
    GOOGLE_CLIENT_ID: ${file(./config/${self:provider.stage}.json):google.client_id}
    GOOGLE_CLIENT_SECRET: ${file(./config/${self:provider.stage}.json):google.client_secret}
    GOOGLE_REDIRECT_URL: ${file(./config/${self:provider.stage}.json):google.redirect_url}
    GOOGLE_SCOPES: ${file(./config/${self:provider.stage}.json):google.scopes}
  httpApi:
    cors: true
functions:
  authorizer:
    # Make sure your file path is correct!
    # (e.g., if your file is in the root folder use server.graphqlHandler )
    # The format is: <FILENAME>.<HANDLER>
    handler: src/authorizer.authorizerHandler # highlight-line
    events:
      - httpApi:
          path: login/
          method: POST
      - httpApi:
          path: login/
          method: GET

  urlGenerator:
    # Make sure your fileurlGenerator path is correct!
    # (e.g., if your file is in the root folder use server.graphqlHandler )
    # The format is: <FILENAME>.<HANDLER>
    handler: src/urlGenerator.urlGeneratorHandler # highlight-line
    events:
      - httpApi:
          path: getMediaUrlAuthentication/
          method: POST
      - httpApi:
          path: getMediaUrlAuthentication/
          method: GET
      - httpApi:
          path: oauth2/idresponse/
          method: POST
      - httpApi:
          path: oauth2/idresponse/
          method: GET
# Omit the following lines if you aren't using TS!
plugins:
  - serverless-plugin-typescript
  - serverless-offline
custom:
  serverless-offline:
    httpPort: 5000
    websocketPort: 5001
    lambdaPort: 5002
