service: test-lambda-authorizer
provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  runtime: nodejs16.x
  environment:
    APP_VERSION: ${file(./package.json):version}
    APP_ENV: ${self:provider.stage}
    APP_TEST: ${file(./config/${self:provider.stage}.json):aws.test}
  httpApi:
    cors: true
functions:
  authorizer:
    # Make sure your file path is correct!
    # (e.g., if your file is in the root folder use server.graphqlHandler )
    # The format is: <FILENAME>.<HANDLER>
    handler: src/authorizer.authorizerHandler # highlight-line
    events:
      - httpApi:
          path: /
          method: POST
      - httpApi:
          path: /
          method: GET
# Omit the following lines if you aren't using TS!
plugins:
  - serverless-plugin-typescript
  - serverless-offline
custom:
  serverless-offline:
    httpPort: 5000
    websocketPort: 5001
    lambdaPort: 5002
