service: apollo-lambda
provider:
  name: aws
  runtime: nodejs16.x
  environment:
    APP_VERSION: ${file(./package.json):version}
    APP_ENV: ${param:environment, 'dev'}
  httpApi:
    cors: true
functions:
  graphql:
    # Make sure your file path is correct!
    # (e.g., if your file is in the root folder use server.graphqlHandler )
    # The format is: <FILENAME>.<HANDLER>
    handler: src/server.graphqlHandler # highlight-line
    events:
      - httpApi:
          path: /
          method: POST
      - httpApi:
          path: /
          method: GET
# Omit the following lines if you aren't using TS!
plugins:
  - serverless-plugin-typescript
  - serverless-offline
