service: apollo-lambda
provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  runtime: nodejs16.x
  environment:
    APP_VERSION: ${file(./package.json):version}
    APP_ENV: ${param:environment, 'dev'}
    URL_USERS: ${file(./config/${self:provider.stage}.json):lambdaUsers.url}
    URL_AUTH: ${file(./config/${self:provider.stage}.json):lambdaAuthorizer.url}
  httpApi:
    cors: true
functions:
  graphql:
    # Make sure your file path is correct!
    # (e.g., if your file is in the root folder use server.graphqlHandler )
    # The format is: <FILENAME>.<HANDLER>
    handler: src/server.graphqlHandler # highlight-line
    events:
      - httpApi:
          path: /
          method: POST
      - httpApi:
          path: /
          method: GET
# Omit the following lines if you aren't using TS!
plugins:
  - serverless-esbuild
  - serverless-offline
custom:
  serverless-offline:
    httpPort: 4000
    websocketPort: 4001
    lambdaPort: 4002
  esbuild:
    bundle: true
    minify: false
